### ISSUE TITLE
Problem pip install git+https://github.com/csteinmetz1/pyloudnorm

### ISSUE THREAD

**Issue by joachimpoutaraud** [csteinmetz1/pyloudnorm#31]
Hi I can't manage to install pyloudnorm or pip install git+https://github.com/csteinmetz1/pyloudnorm properly.

Do you have any issue ? Here is the error appearing when trying to install pip git+https://github.com/csteinmetz1/pyloudnorm on Anaconda Prompt :

ERROR: Command errored out with exit status 1:
     command: 'C:\Users\joachim\anaconda3\envs\sound\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\joachim\\AppData\\Local\\Temp\\pip-req-build-iucuvly5\\setup.py'"'"'; __file__='"'"'C:\\Users\\joachim\\AppData\\Local\\Temp\\pip-req-build-iucuvly5\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\joachim\AppData\Local\Temp\pip-pip-egg-info-n_vt7rdx'
         cwd: C:\Users\joachim\AppData\Local\Temp\pip-req-build-iucuvly5\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\joachim\AppData\Local\Temp\pip-req-build-iucuvly5\setup.py", line 4, in <module>
        long_description = fh.read()
      File "C:\Users\joachim\anaconda3\envs\sound\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3621: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by csteinmetz1** [comment]
Hi @joachimpoutaraud and thanks for your interest in pyloudnorm. 

There may be an issue in the `setup.py` file according a similar issue [here](https://stackoverflow.com/questions/60200727/unicodedecodeerror-charmap-codec-cant-decode-byte-0x81-in-position-73776). I think it could be related to the default encoding on Unix vs. Windows, as it appears you are on Windows. 

I won't be able to look into this until later this week. If you are interested in trying it out, I would be interested to see what happens if you modify line 3 of `setup.py` to include explicit encoding as shown in this example:

```
with open(path.join(this_directory, 'README.md'), encoding='utf-8') as f:
    long_description = f.read()
```
