### ISSUE TITLE
Loudness normalization results in clipping

### ISSUE THREAD

**Issue by nicemanis** [csteinmetz1/pyloudnorm#35]
The peak normalization seems to be working correctly, but the loudness normalization always results in clipping. I tried using both few second clip and a long multiple hour audio.

Here is the code:
```
def normalize_wav(wav, sampling_rate):
    # peak normalize audio to -1 dB
    norm_wav = pyln.normalize.peak(wav, -1.0)

    # measure the loudness first
    meter = pyln.Meter(sampling_rate)  # create BS.1770 meter
    loudness = meter.integrated_loudness(norm_wav)

    # loudness normalize audio to -12 dB LUFS
    norm_wav = pyln.normalize.loudness(norm_wav, loudness, -12.0)

    return norm_wav
```

Here are the values after peak normalization and after loudness normalization:
![image](https://user-images.githubusercontent.com/9463816/113291999-87a3b980-92fc-11eb-9fcb-bd643e77f38e.png)
![image](https://user-images.githubusercontent.com/9463816/113292034-95593f00-92fc-11eb-895b-3a74a6f7ee1c.png)

Is this expected behaviour? How should I correctly apply loudness normalization?

**Comment by csteinmetz1** [comment]
Hi @nicemanis, it is expected behaviour to get clipping if you try to loudness normalize a signal at too high a level, without the use of compression. Try normalizing your audio but with a different target dB LUFS level, say -24, instead of -12. You will have to keep lowering this number until no clipping occurs. So a basic starting point would be to choose a lower target loudness.

For some general insight, normalizing to -12 dB LUFS will likely only work when normalizing commercially produced pop music which has very small dynamic range already. If you are normalizing dialog or broadcast sound, a much lower target is standard, at -24 dB LUFS, or even lower to -32 dB LUFS. 

This happens since in order to increase the loudness to your target value (-12 dB LUFS), the gain of the track must be adjusted. In cases where the signal is very dynamic, achieving a high integrated loudness requires increasing the gain by a lot, and this then causes the signal to go beyond -1,1 in the louder portions.

**Comment by nicemanis** [comment]
@csteinmetz1 thank you for the thorough explenation.
