### ISSUE TITLE
Measurement of some inputs inconsistent with other BS.1770 meters

### ISSUE THREAD

**Issue by csteinmetz1** [csteinmetz1/pyloudnorm#4]
I have noticed some inconsistencies between the measurements produced by pyloudnorm and other loudness meters ([Youlean](https://youlean.co/online-loudness-meter/) and Adobe Audition). The measurements are generally close but can differ by up to 0.4 dB LUFS. With other inputs (like the 997 kHz sine wave referenced in the specification) the meters agree. This means that the error is input dependent and leads me to believe the inconsistency may be due to the gating implementation.

**Comment by schtschenok** [comment]
I'll try to help you to investigate this issue, by testing with some different kinds of data, but I'm wondering if you could annotate a little bit better last ~40 lines in loudness.py, name variables in a readable way, so I'll be able to understand a code a little bit better and help you to solve this issue.

**Comment by csteinmetz1** [comment]
I added some new comments that directly reference the equations shown in the [ITU-R BS.1770-4](https://www.itu.int/dms_pubrec/itu-r/rec/bs/R-REC-BS.1770-4-201510-I!!PDF-E.pdf) document. After experimenting with different sine wave inputs I discovered that only lower frequency signals were measured incorrectly so I adjusted the cutoff frequency of the high pass filter and found that this led to consistent measurements. If you are to check some inputs and affirm that they agree with other sources I will close this issue. Thanks for your help!

**Comment by schtschenok** [comment]
@csteinmetz1 I've done a little bit of testing, I've used pyloudnorm, iZotope RX 6, Youlean and loudness-scanner (libebur128).
And yes, I haven't been able to find differences between the results from these meters larger than 0.1 LUFS using sine waves on frequencies higher than 5 Hz. Also I've noticed that loudness-scanner works really bad with DC signals (it reports -19 LUFS on 10 second long -3 dBFS DC signal), but that's a different story I think.
This means that pyloudnorm K-weighting is probably done right.
I've tested some really high frequencies too, and Youlean meter showed some really wrong results on frequencies higher than 20 kHz. This means that I guess Youlean shouldn't be used as a reference on files with a lot of high frequency content.

Also I've created a signal consisting of 1 kHz sine wave with rapidly changing amplitude to test gating.
This is where I got some interesting results. Here is the file.
[gating_test.wav.zip](https://github.com/csteinmetz1/pyloudnorm/files/2071170/gating_test.wav.zip)
pyloudnorm: -3.4 LUFS
RX: -3.3 LUFS
Youlean: -3.6 LUFS
loudness-scanner: -1.6 LUFS
I don't really know how to interpret these results, but I have a feeling that there is something really wrong with loudness-scanner (libebur128) gating algorithm.
Then I decided to try to go a little further, and synthesised some really weird signal, with a lot of amplitude transients, DC, low and high frequency content. Here is the file. 
[really_werid_sound.wav.zip](https://github.com/csteinmetz1/pyloudnorm/files/2071164/really_werid_sound.wav.zip)
I've measured it with pyloudnorm, RX and Youlean and got really different results.
pyloudnorm: -19.6
RX: -18.5
Youlean: -18.8
This file is quite short (~2 seconds), and I thought that this might be a problem. First of all I assumed that you've got gating right, but thought that there may be a difference because different meters may process last blocks in a different ways, so I've padded a file with a 4 seconds of silence in the end. And got pretty much the same results. Then I thought that maybe the reason is in the first blocks. And eureka! Here is the same file as the previous one, but padded with 4 seconds of silence at the beginning and the end, and results are much better!
[really_werid_sound_padded.wav.zip](https://github.com/csteinmetz1/pyloudnorm/files/2071222/really_werid_sound_padded.wav.zip)
pyloudnorm: -19.1
RX: -19
Youlean: -19.3

So, I don't really know how to fix this problem , but I hope this was helpful.

Also thank you for these new comments!

**Comment by schtschenok** [comment]
I've done a little bit more research on this topic and found out more interesting things.
1). I've tried to test different meters (now including Adobe Audition) with a relative gate test from Compliance material for Recommendation ITU-R BS.1770, and pyloudnorm was actually the only meter that is compliant to this standard, other ones resulted in difference of more than allowed 0.1 LUFS from the expected value.
2). With really_weird_sound.wav, actually, Audition showed a result really close to the pyloudnorm.

I think that this issue should be closed, because there is no way to research this topic any further without having a reference meter, which as far as I understand, doesn't exist. Also, there is a reason to believe that pyloudnorm is actually more compliant to BS.1770 than a lot of available meters, but again, there is no way to test it right without a good reference.

**Comment by csteinmetz1** [comment]
My additional testing has also shown very close agreement of Adobe Audition and pyloudnorm on a number of different inputs so I will close this issue unless further testings indicates we should reopen it.
